role: "Agent"
customConfig:
  api:
    address: 127.0.0.1:8686
    enabled: true
  data_dir: /vector-data-dir
  log_schema:
    host_key: host
  sinks:
  #  blackhole_test:
  #    type: "blackhole"
  #    inputs: ["syslog_udp"]
  #    print_interval_secs: 5

  #  emit_syslog:
  #    encoding:
  #      codec: json
  #    inputs:
  #      - vector_timestamp
  #    type: console

    quickwit_logs:
      encoding:
        codec: json
      framing:
        method: newline_delimited
      inputs:
        - vector_timestamp
      method: post
      type: http
      uri: http://quickwit-searcher:7280/api/v1/syslogs/ingest
  sources:
    syslog_tcp:
      address: "0.0.0.0:514"
      mode: "tcp"
      receive_buffer_bytes: 67108864
      type: "syslog"
      decoding:
        codec: "bytes"
    syslog_udp:
      address: "0.0.0.0:514"
      mode: "udp"
      receive_buffer_bytes: 67108864
      type: "syslog"
      decoding:
        codec: "bytes"
    kubernetes_logs:
      type: kubernetes_logs
  transforms:
    vector_timestamp:
      inputs:
      - syslog_tcp
      - syslog_udp
      - kubernetes_logs
      source: |
        # 1. ใช้เวลาที่ Vector รับ log (UTC)
        .vector_time_utc = now()

        # 2. เก็บเป็น Unix timestamp แบบ nanoseconds (สำหรับ indexing ใน Quickwit)
        .index_timestamp = to_unix_timestamp(.vector_time_utc, unit: "nanoseconds")

        # for quickwit and this worked
        #.event_time = format_timestamp!(.timestamp, format: "%+")

        # 3. ลบตัวแปรชั่วคราวออก
        del(.vector_time_utc)
      type: remap
