# SPDX-License-Identifier: Apache-2.0

services:
  frontend:
    image: ghcr.io/traipoap/frontend:latest
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "4321:4321"
    environment:
      - NODE_ENV=development
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
    runtime: youki
    networks:
      - app-network

  backend:
    image: ghcr.io/traipoap/backend:latest
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - QUICKWIT_URL=http://192.168.1.109:7280
      - BACKEND_PORT=8080

    runtime: youki
    networks:
      - app-network

  rust-backend:
    image: ghcr.io/traipoap/rust-backend:latest
    build:
      context: .
      dockerfile: ./docker/rust-backend/Dockerfile
    environment:
      - RUST_LOG=info
      - OPENSSL_DIR=/usr
      - DATABASE_URL=database.db
      - REDIS_URL=redis://192.168.1.109:6379
      - REDIS_PASSWORD=wZN3iHRAmZWZjwpR
      - QUICKWIT_URL=http://192.168.1.109:7280
    volumes:
      - ./export:/app/export
    ports:
      - "8081:8080"
    expose:
      - "8081"
    runtime: youki
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
