---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - curl
      - nfs-common
    state: present

- name: Enable and start qemu-guest-agent
  systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
