- name: Deploy Garage
  hosts: load-balance
  become: true
  roles:
    - garage
  vars:
    garage_version: "2.3.0"
    garage_binaries_dir: /usr/local/bin
    garage_main_binary: "/usr/local/bin/garage"
    garage_system_user: "garage"
    garage_system_group: "garage"
    garage_logging: "netapp=info,garage=info"
    garage_architecture: "{{ansible_architecture}}"

    garage_local_template: "garage.toml.j2"
    garage_config_file: "/etc/garage.toml"
    garage_metadata_dir: "/var/lib/garage"
    garage_data_dir: "/nfs/data"
    my_rpc_secret: "REDACTED_RPC_SECRET"
    my_admin_token: "REDACTED_ADMIN_TOKEN"

    garage_service_template: "garage.service.j2"
    garage_systemd_service: "garage"

    GARAGE_DEFAULT_ACCESS_KEY: "REDACTED_GARAGE_ACCESS_KEY" #"GK$(openssl rand -hex 16)"
    GARAGE_DEFAULT_SECRET_KEY: "REDACTED_GARAGE_SECRET_KEY" #"$(openssl rand -hex 32)"
    GARAGE_DEFAULT_BUCKET: "default-bucket"

  handlers:
    - name: reload systemd
      systemd: daemon_reload=yes
    - name: restart garage
      systemd: name={{garage_systemd_service}} state=restarted
    - name: Check garage status
      systemd: name={{garage_systemd_service}} state=started
