- name: Deploy Garage
  hosts: load-balance
  become: true

  vars_prompt:
    - name: user_input_rpc_secret
      private: true
      prompt: "Enter RPC secret run echo $(openssl rand -hex 32) (blank to generate)"
    - name: user_input_admin_token
      private: true
      prompt: "Enter admin token run echo $(openssl rand -base64 32) (blank to generate)"
    - name: user_input_access_key
      private: true
      prompt: "Enter access key run echo $(openssl rand -hex 32) (blank to generate)"
    - name: user_input_secret_key
      private: true
      prompt: "Enter secret key run echo $(openssl rand -hex 32) (blank to generate)"

  vars:
    garage_version: "2.3.0"
    garage_binaries_dir: /usr/local/bin
    garage_main_binary: "/usr/local/bin/garage"
    garage_system_user: "garage"
    garage_system_group: "garage"
    garage_logging: "netapp=info,garage=info"
    garage_architecture: "{{ansible_architecture}}"

    garage_local_template: "garage.toml.j2"
    garage_config_file: "/etc/garage.toml"
    garage_metadata_dir: "/var/lib/garage"
    garage_data_dir: "/nfs/data"
    my_rpc_secret: "{{ user_input_rpc_secret | default(lookup('password', '/dev/null chars=hexdigits length=64'), true) }}" # Example: "REDACTED_RPC_SECRET"
    my_admin_token: "{{ user_input_admin_token | default(lookup('password', '/dev/null chars=ascii_letters,digits length=64'), true) }}" # Example: "REDACTED_ADMIN_TOKEN"

    garage_service_template: "garage.service.j2"
    garage_systemd_service: "garage"

    GARAGE_DEFAULT_ACCESS_KEY: "{{ user_input_access_key | default('GK' + lookup('password', '/dev/null chars=hexdigits length=32'), true) }}" # Example: "REDACTED_GARAGE_ACCESS_KEY"
    GARAGE_DEFAULT_SECRET_KEY: "{{ user_input_secret_key | default(lookup('password', '/dev/null chars=hexdigits length=64'), true) }}" # Example: "REDACTED_GARAGE_SECRET_KEY"
    GARAGE_DEFAULT_BUCKET: "default-bucket"

  tasks:
    - name: Display generated credentials (Securely)
      ansible.builtin.debug:
        msg:
          - "RPC Secret: {{ my_rpc_secret }}"
          - "Admin Token: {{ my_admin_token }}"
          - "Access Key: {{ GARAGE_DEFAULT_ACCESS_KEY }}"
          - "Secret Key: {{ GARAGE_DEFAULT_SECRET_KEY }}"

  handlers:
    - name: reload systemd
      systemd: daemon_reload=yes
    - name: restart garage
      systemd: name={{garage_systemd_service}} state=restarted
    - name: Check garage status
      systemd: name={{garage_systemd_service}} state=started

  roles:
    - garage
