apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: frontend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1


configMapGenerator:
  - name: lumina-config
    namespace: lumina
    behavior: merge
    literals:
      - LOG_LEVEL=debug

#images:
#  - name: traipoap/frontend
#    newName: traipoap/frontend
#    newTag: dev-20260712-10

#  - name: traipoap/backend
#    newName: traipoap/backend
#    newTag: dev-20260712-10
