    - name: Install Flux CLI on Master node
      shell: curl -s https://fluxcd.io/install.sh | sudo bash
      args:
        creates: /usr/local/bin/flux

    - name: Bootstrap Flux to bind cluster with GitHub
      shell: |
        flux bootstrap github \
          --owner={{ github_owner }} \
          --repository={{ github_repo }} \
          --branch=main \
          --path=./clusters/dev \
          --personal
      environment:
        GITHUB_TOKEN: "{{ app_git_secret }}"
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Create secret for GitHub token
      shell: |
        kubectl create secret generic app-git-secret \
          --namespace=flux-system \
          --from-literal=username={{ github_owner }} \
          --from-literal=password={{ app_git_secret }}
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Create namespace for {{ namespace }}
      shell: kubectl create namespace {{ namespace }}
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Create secret for GitHub docker-registry
      shell: |
        kubectl -n {{ namespace }} create secret docker-registry github-registry \
          --docker-server ghcr.io \
          --docker-username {{ github_owner }} \
          --docker-password {{ github_registry }} \
          --docker-email {{ github_owner }}@hotmail.com
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true
