    - name: Install Flux CLI on Master node
      shell: curl -s https://fluxcd.io/install.sh | sudo bash
      args:
        creates: /usr/local/bin/flux

    - name: Bootstrap Flux to bind cluster with GitHub/GitLab
      shell: |
        flux bootstrap github \
          --owner={{ github_owner }} \
          --repository={{ github_repo }} \
          --branch=main \
          --path=./clusters/my-cluster \
          --personal
      environment:
        GITHUB_TOKEN: "{{ github_personal_access_token }}"
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Create secret for GitHub token
      shell: |
        kubectl create secret generic app-git-secret \
          --namespace=flux-system \
          --from-literal=username={{ github_owner }} \
          --from-literal=password={{ github_personal_access_token }}
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Install GatewayAPI https://github.com/kubernetes-sigs/gateway-api/releases
      shell: |
        kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.1/standard-install.yaml
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true
