# SPDX-License-Identifier: Apache-2.0

    - name: Install Flux CLI on Master node
      shell: curl -s https://fluxcd.io/install.sh | sudo bash
      args:
        creates: /usr/local/bin/flux

    - name: Bootstrap Flux to bind cluster with GitHub
      shell: |
        flux bootstrap github \
          --components-extra=image-reflector-controller,image-automation-controller,source-watcher \
          --owner={{ github_owner }} \
          --repository={{ github_repo }} \
          --branch=main \
          --path=./clusters/staging \
          --read-write-key \
          --personal

      environment:
        GITHUB_TOKEN: "{{ app_git_secret }}"
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Create namespace for {{ ns_name }}
      shell: kubectl create namespace {{ ns_name }}
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true

    - name: Create secret for GitHub docker-registry
      shell: |
        kubectl -n {{ ns_name }} create secret docker-registry github-registry \
          --docker-server ghcr.io \
          --docker-username {{ github_owner }} \
          --docker-password {{ github_registry }} \
          --docker-email {{ github_owner }}@hotmail.com
      environment:
        KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      run_once: true
      ignore_errors: true
