    - name: Install K3s server
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
          --node-ip={{ node_ip }} \
          --write-kubeconfig-mode 644 \
          --disable=traefik
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure K3s is started
      systemd:
        name: k3s
        state: started
        enabled: true
