apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-management-ingress
  namespace: log-management
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: log-management.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 4321
  tls:
    - hosts:
        - log-management.local
      secretName: log-management-tls
