name: Backend Build & Deploy

on:
  push:
    branches: [main]
    paths:
      - 'docker/backend/**'
      - 'backend/**'

jobs:
  call-build:
    uses: ./.github/workflows/build-and-push.yml
    with:
      service: backend
      dockerfile: ./docker/backend/Dockerfile
      image_name: ghcr.io/traipoap/backend
    secrets: inherit
