# SPDX-License-Identifier: Apache-2.0

name: Docker Build and Push to GHCR

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      dockerfile:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Log in to GHCR
        run: podman login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_REGISTRY }}

      - name: Build image
        run: podman build -t ghcr.io/traipoap/${{ inputs.service }}:0.0.${{ github.run_number }} --build-arg VERSION=0.0.${{ github.run_number }} -f ${{ inputs.dockerfile }} .

      - name: Push image
        run: podman push ghcr.io/traipoap/${{ inputs.service }}:0.0.${{ github.run_number }}
